services:
  urlshortener.frontend:
    build:
      target: final
    ports:
      - "80"
      - "443"
      - "11111" # Silo port
      - "11112" # Gateway port
    env_file:
      - local.debug.azure.env
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    volumes:
      - ./devCerts/https:/root/.aspnet/https:ro
      - ~/.vsdbg:/remote_debugger:rw

  urlshortener.backend.silohost:
    build:
      target: final
    env_file:
      - local.debug.azure.env